
#ifndef PCI_DEVICE_ID_CCD_HFC4S
#define PCI_DEVICE_ID_CCD_HFC4S		0x08B4
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_PMX2S
#define PCI_SUBDEVICE_ID_CCD_PMX2S	0x1234
#endif
#ifndef PCI_DEVICE_ID_CCD_HFC8S
#define PCI_DEVICE_ID_CCD_HFC8S		0x16B8
#endif
#ifndef PCI_DEVICE_ID_CCD_HFCE1
#define PCI_DEVICE_ID_CCD_HFCE1		0x30B1
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_SPD4S
#define PCI_SUBDEVICE_ID_CCD_SPD4S	0x3136
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_SPDE1
#define PCI_SUBDEVICE_ID_CCD_SPDE1	0x3137
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_IOB4ST
#define PCI_SUBDEVICE_ID_CCD_IOB4ST	0xB520
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_IOB8STR
#define PCI_SUBDEVICE_ID_CCD_IOB8STR	0xB521
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_IOB8ST
#define PCI_SUBDEVICE_ID_CCD_IOB8ST	0xB522
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_IOB1E1
#define PCI_SUBDEVICE_ID_CCD_IOB1E1	0xB523
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_SWYX4S
#define PCI_SUBDEVICE_ID_CCD_SWYX4S	0xB540
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_JH4S20
#define PCI_SUBDEVICE_ID_CCD_JH4S20	0xB550
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_IOB8ST_1
#define PCI_SUBDEVICE_ID_CCD_IOB8ST_1	0xB552
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_JHSE1
#define PCI_SUBDEVICE_ID_CCD_JHSE1	0xB553
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_BN4S
#define PCI_SUBDEVICE_ID_CCD_BN4S	0xB560
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_BN8S
#define PCI_SUBDEVICE_ID_CCD_BN8S	0xB562
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_BNE1
#define PCI_SUBDEVICE_ID_CCD_BNE1	0xB563
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_BNE1D
#define PCI_SUBDEVICE_ID_CCD_BNE1D	0xB564
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_BNE1DP
#define PCI_SUBDEVICE_ID_CCD_BNE1DP	0xB565
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_BN2S
#define PCI_SUBDEVICE_ID_CCD_BN2S	0xB566
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_BN1SM
#define PCI_SUBDEVICE_ID_CCD_BN1SM	0xB567
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_BN4SM
#define PCI_SUBDEVICE_ID_CCD_BN4SM	0xB568
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_BN2SM
#define PCI_SUBDEVICE_ID_CCD_BN2SM	0xB569
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_BNE1M
#define PCI_SUBDEVICE_ID_CCD_BNE1M	0xB56A
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_BN8SP
#define PCI_SUBDEVICE_ID_CCD_BN8SP	0xB56B
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_HFC4S
#define PCI_SUBDEVICE_ID_CCD_HFC4S	0xB620
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_HFC8S
#define PCI_SUBDEVICE_ID_CCD_HFC8S	0xB622
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_HFCE1
#define PCI_SUBDEVICE_ID_CCD_HFCE1	0xC523
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_OV2S
#define PCI_SUBDEVICE_ID_CCD_OV2S	0xE884
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_OV4S
#define PCI_SUBDEVICE_ID_CCD_OV4S	0xE888
#endif
#ifndef PCI_SUBDEVICE_ID_CCD_OV8S
#define PCI_SUBDEVICE_ID_CCD_OV8S	0xE998
#endif

#ifndef PCI_VENDOR_ID_DIGIUM
#define PCI_VENDOR_ID_DIGIUM		0xd161
#define PCI_DEVICE_ID_DIGIUM_HFC4S	0xb410
#endif

#ifndef PCI_SUBDEVICE_ID_CCD_JH8S
#define PCI_SUBDEVICE_ID_CCD_JH8S	0xB55B
#endif

